services:
  - type: web
    name: mtf-video-editing
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
